/* Generated by tools/group-sample.py from prototypes/consolidation: do not edit by hand. */
(function (root) { root.HfgGroupSample = {
 "note": "Fictional group shaped like HFG's ($000), from prototypes/consolidation. Generated by tools/group-sample.py.",
 "years": [
  "FY2026",
  "FY2027",
  "FY2028"
 ],
 "yearStart": [
  "1 April 2025",
  "1 April 2026",
  "1 April 2027"
 ],
 "entities": [
  {
   "code": 9000,
   "name": "Foundation",
   "parent": null,
   "held": 1.0,
   "gst": true,
   "role": "Parent; pays shared costs and on-charges them at cost",
   "status": "Actual",
   "from": "1 April 2025",
   "own": {
    "surplus": [
     -100.0,
     -90.0,
     -0.0
    ],
    "na": [
     5900.0,
     5810.0,
     5810.0
    ]
   }
  },
  {
   "code": 9001,
   "name": "BuildCo Ltd",
   "parent": 9000,
   "held": 1.0,
   "gst": true,
   "role": "Builds for the development LPs with a margin",
   "status": "Actual",
   "from": "1 April 2025",
   "own": {
    "surplus": [
     690.0,
     585.0,
     255.0
    ],
    "na": [
     1190.0,
     1775.0,
     2030.0
    ]
   }
  },
  {
   "code": 9002,
   "name": "DevManager Ltd",
   "parent": 9000,
   "held": 1.0,
   "gst": true,
   "role": "Development management fees with a margin",
   "status": "Actual",
   "from": "1 April 2025",
   "own": {
    "surplus": [
     135.0,
     30.0,
     -0.0
    ],
    "na": [
     335.0,
     365.0,
     365.0
    ]
   }
  },
  {
   "code": 9003,
   "name": "PropManager Ltd",
   "parent": 9000,
   "held": 1.0,
   "gst": true,
   "role": "Manages the Fund's homes for a fee plus GST",
   "status": "Actual",
   "from": "1 April 2025",
   "own": {
    "surplus": [
     20.0,
     120.0,
     240.0
    ],
    "na": [
     120.0,
     240.0,
     480.0
    ]
   }
  },
  {
   "code": 9004,
   "name": "Holdings LP",
   "parent": 9000,
   "held": 1.0,
   "gst": false,
   "role": "Sub-group head; due diligence, loans to LPs",
   "status": "Actual",
   "from": "1 April 2025",
   "own": {
    "surplus": [
     -0.0,
     43.2,
     136.656
    ],
    "na": [
     3500.0,
     3543.2,
     3679.856
    ]
   }
  },
  {
   "code": 9005,
   "name": "Devco LP",
   "parent": 9004,
   "held": 1.0,
   "gst": false,
   "role": "Sub-group head for the development LPs",
   "status": "Actual",
   "from": "1 April 2025",
   "own": {
    "surplus": [
     -0.0,
     -0.0,
     -0.0
    ],
    "na": [
     1800.0,
     1800.0,
     1800.0
    ]
   }
  },
  {
   "code": 9006,
   "name": "Dev LP A",
   "parent": 9005,
   "held": 1.0,
   "gst": false,
   "role": "Builds site SA and sells the portfolio to the Fund",
   "status": "Actual",
   "from": "1 April 2025",
   "own": {
    "surplus": [
     -0.0,
     680.0,
     -0.0
    ],
    "na": [
     900.0,
     1580.0,
     1580.0
    ]
   }
  },
  {
   "code": 9007,
   "name": "Dev LP B",
   "parent": 9005,
   "held": 1.0,
   "gst": false,
   "role": "Builds site SB on a Holdings loan",
   "status": "Actual",
   "from": "1 April 2025",
   "own": {
    "surplus": [
     -0.0,
     -0.0,
     -0.0
    ],
    "na": [
     700.0,
     700.0,
     700.0
    ]
   }
  },
  {
   "code": 9008,
   "name": "Housing Fund LP",
   "parent": 9004,
   "held": 0.6,
   "gst": false,
   "role": "Holds the portfolios; external investors hold 40%",
   "status": "Actual",
   "from": "1 April 2025",
   "own": {
    "surplus": [
     -0.0,
     29.0,
     440.0
    ],
    "na": [
     2000.0,
     2029.0,
     2269.0
    ]
   }
  },
  {
   "code": 9009,
   "name": "Fund Dev LP",
   "parent": 9008,
   "held": 1.0,
   "gst": false,
   "role": "Builds site SF for the Fund",
   "status": "Actual",
   "from": "1 April 2025",
   "own": {
    "surplus": [
     -0.0,
     -0.0,
     -0.0
    ],
    "na": [
     600.0,
     600.0,
     600.0
    ]
   }
  },
  {
   "code": 9010,
   "name": "Partner LP",
   "parent": 9004,
   "held": 0.7,
   "gst": false,
   "role": "Partly owned; sells site SP to the Fund",
   "status": "Actual",
   "from": "1 April 2025",
   "own": {
    "surplus": [
     -0.0,
     300.0,
     -0.0
    ],
    "na": [
     1000.0,
     1300.0,
     1300.0
    ]
   }
  }
 ],
 "groups": [
  {
   "head": 9000,
   "name": "Foundation group",
   "surplus": [
    30.0,
    194.0,
    1082.5
   ],
   "na": [
    7130.0,
    7324.0,
    8326.5
   ],
   "elimSurplus": [
    -715.0,
    -1503.2,
    10.844
   ],
   "elimNa": [
    -10915.0,
    -12418.2,
    -12287.356
   ],
   "nciSurplus": [
    0.0,
    11.6,
    176.0
   ],
   "nci": [
    1100.0,
    1111.6,
    1207.6
   ]
  },
  {
   "head": 9004,
   "name": "Holdings group",
   "surplus": [
    -40.0,
    29.0,
    580.0
   ],
   "na": [
    4560.0,
    4589.0,
    5089.0
   ],
   "elimSurplus": [
    -40.0,
    -1023.2,
    3.344
   ],
   "elimNa": [
    -5940.0,
    -6963.2,
    -6839.856
   ],
   "nciSurplus": [
    0.0,
    11.6,
    176.0
   ],
   "nci": [
    1100.0,
    1111.6,
    1207.6
   ]
  },
  {
   "head": 9005,
   "name": "Devco group",
   "surplus": [
    -0.0,
    680.0,
    -0.0
   ],
   "na": [
    1800.0,
    2480.0,
    2480.0
   ],
   "elimSurplus": [
    -0.0,
    0.0,
    -0.0
   ],
   "elimNa": [
    -1600.0,
    -1600.0,
    -1600.0
   ],
   "nciSurplus": [
    0.0,
    0.0,
    0.0
   ],
   "nci": [
    0.0,
    0.0,
    0.0
   ]
  },
  {
   "head": 9008,
   "name": "Fund group",
   "surplus": [
    -0.0,
    29.0,
    440.0
   ],
   "na": [
    2000.0,
    2029.0,
    2269.0
   ],
   "elimSurplus": [
    -0.0,
    0.0,
    0.0
   ],
   "elimNa": [
    -600.0,
    -600.0,
    -600.0
   ],
   "nciSurplus": [
    0.0,
    0.0,
    0.0
   ],
   "nci": [
    0.0,
    0.0,
    0.0
   ]
  },
  {
   "head": 9010,
   "name": "Partner LP",
   "surplus": [
    -0.0,
    300.0,
    -0.0
   ],
   "na": [
    1000.0,
    1300.0,
    1300.0
   ],
   "elimSurplus": [
    -0.0,
    0.0,
    -0.0
   ],
   "elimNa": [
    0.0,
    0.0,
    0.0
   ],
   "nciSurplus": [
    0.0,
    0.0,
    0.0
   ],
   "nci": [
    0.0,
    0.0,
    0.0
   ]
  }
 ]
}; })(typeof globalThis !== 'undefined' ? globalThis : this);
