"""The budget demo: a fictional maintenance and construction contractor, as a recipe the engine builds.

    python -m examples.budget_model.recipe      # writes library/hfg/recipes/budget_model.json

Everything here is fictional demo data, shaped like a contractor's budget against actuals: three
business units (Auckland and Waikato maintenance, capital works), revenue and direct costs by GL
code spread by seasonality profiles, salaries and overheads by GL code, the approved budget saved
and a reforecast saved each month, and next year's budget being built. Its history (April 2025 to
September 2026) is generated by running the model's own logic over what "happened", with noise,
from the opening balance sheet at 31 March 2025.
"""

from __future__ import annotations

import json
import random
from pathlib import Path

from examples.full_model.recipe import HISTORY_ROWS, consistent, r2, saved_versions
from examples.full_model.reference import Inst, run

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "library" / "hfg" / "recipes" / "budget_model.json"

T = 36                 # April 2025 to March 2028
LAST_ACTUAL = 18       # September 2026
START = (2025, 4)
FY_END = 3
BUDGET_FIRST, BUDGET_MONTHS = 25, 12   # FY2028, the budget being built
SEED = 20261008
rng = random.Random(SEED)


def norm(xs: list[float]) -> list[float]:
    s = sum(xs)
    out = [round(x / s, 4) for x in xs]
    out[-1] = round(1 - sum(out[:-1]), 4)
    return out


# Seasonality by month of the financial year (April first): maintenance peaks in late spring and
# summer, capital works slow over winter and stop for the Christmas break.
MAINTENANCE = norm([0.085, 0.085, 0.080, 0.079, 0.082, 0.085, 0.088, 0.090, 0.076, 0.072, 0.086, 0.092])
CAPITAL = norm([0.088, 0.084, 0.074, 0.070, 0.077, 0.085, 0.091, 0.094, 0.070, 0.058, 0.099, 0.110])
EVEN = [1 / 12] * 12
PROFILES = [MAINTENANCE, CAPITAL, EVEN]

# Business units: their position in the drop-down (1 is Whole business).
AKL, WKO, CAP = 2, 3, 4


def fy_index(t: int) -> int:
    """0 for FY2026, 1 for FY2027, 2 for FY2028."""
    return t // 12


def fy_month(t: int) -> int:
    return t % 12 + 1


def phased(annual_fy27: float, growth: float, profile: int, t: int, noise: float = 0.0, actual: bool = False) -> float:
    """What a line does in month t: FY2027's annual amount, less a year's growth for FY2026 and plus one for FY2028,
    spread by the profile; actual months carry noise."""
    v = annual_fy27 * (1 + growth) ** (fy_index(t) - 1) * PROFILES[profile - 1][fy_month(t) - 1]
    return r2(v * (1 + rng.uniform(-noise, noise))) if actual else r2(v)


def stepped(base: float, rise: float) -> list[float]:
    return [r2(base * (1 + rise) ** fy_index(t)) for t in range(T)]


# GL lines: (module, name, business unit, FY2027 annual budget, growth a year, profile, extra settings, noise, scenario)
LINES = [
    ("fm.revenue", "4100 Reactive maintenance, Auckland", AKL, 6_200_000, 0.05, 1, {"gst": 1, "collect": 2}, 0.06, [0, 0.05, -0.08]),
    ("fm.revenue", "4110 Planned maintenance, Auckland", AKL, 3_100_000, 0.04, 3, {"gst": 1, "collect": 2}, 0.02, [0, 0.03, -0.05]),
    ("fm.revenue", "4100 Reactive maintenance, Waikato", WKO, 2_800_000, 0.06, 1, {"gst": 1, "collect": 2}, 0.07, [0, 0.05, -0.08]),
    ("fm.revenue", "4110 Planned maintenance, Waikato", WKO, 1_400_000, 0.04, 3, {"gst": 1, "collect": 2}, 0.02, [0, 0.03, -0.05]),
    ("fm.revenue", "4300 Capital works contracts", CAP, 7_500_000, 0.08, 2, {"gst": 1, "collect": 3}, 0.10, [0, 0.10, -0.20]),
    ("fm.cogs", "5100 Wages, Auckland", AKL, 3_400_000, 0.045, 1, {"gst": 3, "stock": 1, "pay": 1}, 0.03, [0, 0, 0.03]),
    ("fm.cogs", "5100 Wages, Waikato", WKO, 1_600_000, 0.045, 1, {"gst": 3, "stock": 1, "pay": 1}, 0.03, [0, 0, 0.03]),
    ("fm.cogs", "5100 Wages, Capital works", CAP, 1_900_000, 0.05, 2, {"gst": 3, "stock": 1, "pay": 1}, 0.04, [0, 0, 0.03]),
    ("fm.cogs", "5200 Subcontractors, Auckland", AKL, 1_500_000, 0.05, 1, {"gst": 1, "stock": 1, "pay": 2}, 0.08, [0, 0, 0.04]),
    ("fm.cogs", "5200 Subcontractors, Capital works", CAP, 3_200_000, 0.08, 2, {"gst": 1, "stock": 1, "pay": 2}, 0.10, [0, 0, 0.04]),
    ("fm.cogs", "5300 Consumables and materials, Auckland", AKL, 900_000, 0.05, 1, {"gst": 1, "stock": 1, "pay": 2}, 0.07, [0, 0, 0.05]),
    ("fm.cogs", "5300 Consumables and materials, Waikato", WKO, 450_000, 0.05, 1, {"gst": 1, "stock": 1, "pay": 2}, 0.07, [0, 0, 0.05]),
    ("fm.cogs", "5300 Materials, Capital works", CAP, 900_000, 0.08, 2, {"gst": 1, "stock": 1, "pay": 2}, 0.09, [0, 0, 0.05]),
    ("fm.cogs", "5400 Fleet, Auckland", AKL, 380_000, 0.04, 3, {"gst": 1, "stock": 1, "pay": 2}, 0.04, [0, 0, 0.03]),
    ("fm.cogs", "5400 Fleet, Waikato", WKO, 200_000, 0.04, 3, {"gst": 1, "stock": 1, "pay": 2}, 0.04, [0, 0, 0.03]),
    ("fm.opex", "6200 Premises", 1, 360_000, 0.03, 3, {"gst": 1, "pay": 2}, 0.01, [0, 0, 0.03]),
    ("fm.opex", "6300 IT and software", 1, 180_000, 0.06, 3, {"gst": 1, "pay": 2}, 0.05, [0, 0, 0.03]),
    ("fm.opex", "6400 Insurance", 1, 120_000, 0.07, 3, {"gst": 2, "pay": 1}, 0.0, [0, 0, 0.03]),
    ("fm.opex", "6500 Professional fees", 1, 90_000, 0.03, 3, {"gst": 1, "pay": 2}, 0.20, [0, 0, 0.03]),
    ("fm.opex", "6600 Travel and accommodation, Waikato", WKO, 60_000, 0.03, 1, {"gst": 1, "pay": 2}, 0.15, [0, 0, 0.03]),
    ("fm.opex", "6700 Training and safety", 1, 80_000, 0.04, 3, {"gst": 1, "pay": 2}, 0.12, [0, 0, 0.03]),
]


def instances(model: bool) -> list[Inst]:
    """The recipe's instances. `model` False gives the history generator's version: each GL line as the
    amounts that happened (its budget phasing with noise) instead of an annual budget and a profile."""
    rng.seed(SEED)
    n: dict[str, int] = {}

    def add(module: str, name: str | None = None, settings: dict | None = None, data: dict | None = None) -> Inst:
        n[module] = n.get(module, 0) + 1
        return Inst(module, n[module], settings or {}, name, data or {})

    actual = lambda t: t < LAST_ACTUAL
    out = [
        add("fm.season", "Maintenance (summer peak)", {"method": 1}, {"series": {"share": MAINTENANCE}}),
        add("fm.season", "Capital works (Christmas break)", {"method": 1}, {"series": {"share": CAPITAL}}),
        add("fm.season", "Even spread", {"method": 2}),
        add("fm.season_table"),
        add("fm.business_unit", "Auckland maintenance"),
        add("fm.business_unit", "Waikato maintenance"),
        add("fm.business_unit", "Capital works"),
    ]
    for module, name, bu, annual, growth, profile, extra, noise, scen in LINES:
        key = "revenue" if module == "fm.revenue" else "cost"
        amounts = [phased(annual, growth, profile, t, noise, actual(t)) for t in range(T)]
        method = 4 if model else (1 if module != "fm.cogs" else 2)
        settings = {"method": method, "bu": bu, **extra}
        if model:
            settings.update({"profile": profile, "annual": annual, "escalation": growth})
        out.append(add(module, name, settings, {"series": {} if model else {"amount": amounts}, "scenarios": {key: scen}}))
    out += [
        add("fm.staff", "6100 Salaries, operations management", {"kiwisaver": 0.03},
            {"series": {"fte": [8] * 12 + [9] * 24, "salary": stepped(118_000, 0.035)}, "scenarios": {"salaries": [0, 0.02, 0]}}),
        add("fm.staff", "6110 Salaries, support office", {"kiwisaver": 0.03},
            {"series": {"fte": [11] * 15 + [12] * 21, "salary": stepped(72_000, 0.03)}, "scenarios": {"salaries": [0, 0.02, 0]}}),
        add("fm.other_income", "Sundry income", {}, {"series": {"amount": [r2(rng.uniform(1_000, 4_000)) if actual(t) else 2_000 for t in range(T)]}}),
        add("fm.other_expense", "Donations", {}, {"series": {"amount": [1_500] * T}}),
        add("fm.collection", "Trade debtors", {"days": 20}, {"opening": {"closing": 1_050_000}}),
        add("fm.collection", "Maintenance clients", {"days": 30}, {"opening": {"closing": 760_000}}),
        add("fm.collection", "Capital works clients", {"days": 45}, {"opening": {"closing": 1_120_000}}),
        add("fm.payment", "Trade creditors", {"days": 35}, {"opening": {"closing": 640_000}}),
        add("fm.payroll", None, {"withheld": 0.22, "leave": 1.1}, {"opening": {"payable": 260_000, "leave": 690_000}}),
        add("fm.fixed_asset", "Plant and fleet", {"rate": 0.25}, {"opening": {"nbv": 1_850_000}}),
        add("fm.fixed_asset", "Workshop and office", {"rate": 0.08}, {"opening": {"nbv": 420_000}}),
        add("fm.intangible", "Job costing system", {"rate": 0.3}, {"opening": {"nbv": 160_000}}),
        add("fm.capex", "Fleet replacement", {"class": 1, "gst": 1},
            {"series": {"amount": [140_000 if t in (2, 14, 26) else 90_000 if t in (8, 20, 32) else 0 for t in range(T)]}}),
        add("fm.capex", "Tools and plant", {"class": 1, "gst": 1}, {"series": {"amount": [r2(rng.uniform(4_000, 12_000)) if actual(t) else 8_000 for t in range(T)]}}),
        add("fm.capex", "Workshop fit-out", {"class": 2, "gst": 1}, {"series": {"amount": [65_000 if t == 9 else 0 for t in range(T)]}}),
        add("fm.debt", "Equipment finance", {"rate": 0.079}, {"series": {"draw": [0] * T, "repay": [22_000] * T},
            "opening": {"balance": 1_100_000}, "scenarios": {"rate_now": [0, -0.1, 0.2]}}),
        add("fm.debt", "Working capital facility", {"rate": 0.085},
            {"series": {"draw": [250_000 if t in (3, 15, 27) else 0 for t in range(T)], "repay": [125_000 if t in (8, 9, 20, 21, 32, 33) else 0 for t in range(T)]},
             "opening": {"balance": 0}, "scenarios": {"rate_now": [0, -0.1, 0.2]}}),
        add("fm.equity", None, {"payout": 0.5, "delay": 3, "limit": True},
            {"series": {"issue": [0] * T}, "opening": {"capital": 1_500_000, "payable": 260_000}}),
        add("fm.gst", None, {"rate": 0.15, "cycle": 2}, {"opening": {"payable": 210_000}}),
        add("fm.income_tax", None, {"rate": 0.28, "uplift": 0.05}, {"opening": {"payable": 120_000}}),
        add("fm.interest_cash", None, {"rate": 0.025, "od_rate": 0.095}),
        add("fm.other_ca", "Prepayments", {}, {"series": {"change": [r2(rng.uniform(-6_000, 6_000)) for _ in range(T)]}, "opening": {"balance": 95_000}}),
        add("fm.other_cl", "Accruals", {}, {"series": {"change": [r2(rng.uniform(-8_000, 8_000)) for _ in range(T)]}, "opening": {"balance": 180_000}}),
        add("fm.statements", None, {}, {"opening": {"cash": 1_250_000}}),
        add("fm.checks"),
        # Dashboards for FY2027, the year the actuals run into
        add("fm.income_summary", None, {"year": 2}),
        add("fm.cash_summary", None, {"year": 2}),
        add("fm.budget_summary", None, {"year": 2, "compare": 1}),
        add("fm.bu_summary", None, {"year": 2}),
        add("fm.version_comparison", None, {"line": 1, "month": 18, "compare": 1, "compare2": 2}),
        add("fm.budget", None, {"target": 1_250_000}),
        add("fm.versions"),
        add("fm.budget_report", None, {"year": 2, "compare": 1}),
    ]
    return out


OPENING = {
    "assets": 1_250_000 + 1_050_000 + 760_000 + 1_120_000 + 95_000 + 1_850_000 + 420_000 + 160_000,
    "liabilities": 640_000 + 260_000 + 690_000 + 210_000 + 120_000 + 260_000 + 180_000 + 1_100_000,
    "capital": 1_500_000,
}
OPENING_RETAINED = OPENING["assets"] - OPENING["liabilities"] - OPENING["capital"]

# What the model cannot know but the generator needs: GST for March 2025 accrued, the tax years
# before the model, and the FY2025 dividend declared in March 2025.
GEN_INIT = {
    "gst_period_end_prev": 0.0, "gst_accrued_prev": 210_000.0, "gst_due_prev": 0.0,
    "tax_ytd_prev": 520_000.0, "tax_last_year_prev": 450_000.0, "tax_two_years_prev": 400_000.0,
    "tax_paid_fy_prev": 2 * 450_000 * 1.05 / 3,
    "npat_ytd_prev": 0.0, "declared_before": [260_000.0, 0, 0, 0, 0, 0],
}


def generate() -> tuple[list[Inst], dict]:
    gen = instances(model=False)
    for i in gen:
        if i.module == "fm.equity":
            i.data.setdefault("opening", {})["retained"] = OPENING_RETAINED
    rows = run(gen, T, last_actual=0, fy_end=FY_END, start_month=START[1], start_year=START[0], init=GEN_INIT)
    model = instances(model=True)
    for g, m in zip(gen, model):
        m.data["opening"] = dict(g.data.get("opening", {}))
        keys = HISTORY_ROWS.get(m.module, [])
        if keys:
            src = "fs" if m.module == "fm.statements" else g.uid
            m.data["history"] = {k: [r2(v) for v in rows[f"{src}/{k}"][:LAST_ACTUAL]] for k, _ in keys}
    consistent(model, rows, LAST_ACTUAL)
    budgets = [(1, 0, 1.0, "Approved", "2025-03-20"), (2, 12, 1.0, "Approved", "2026-03-24")]
    for i in model:
        if i.module == "fm.versions":
            i.data["versions"] = saved_versions(model, T, START, FY_END, LAST_ACTUAL, budgets)
    return model, rows


def recipe() -> dict:
    model, _ = generate()
    return {
        "title": "Maintenance and construction budget",
        "entity": {"name": "Home Construction Limited (fictional demo)", "brand": "HCL"},
        "preparedBy": "Prepared by Group Finance",
        "notes": [
            "Fictional demo data shaped like a contractor's budget against actuals: three business units, GL lines spread by seasonality profiles.",
            "Actual months (April 2025 to September 2026) read the historical statements; later months follow the budget by GL code.",
            "The approved FY2027 budget and a reforecast for every month are saved as values (Versions); FY2028 is the budget being built.",
        ],
        "timeline": {"start": f"{START[0]}-{START[1]:02d}", "fyEndMonth": FY_END, "lastActual": LAST_ACTUAL, "denomination": "$000",
                     "budget": {"first": BUDGET_FIRST, "months": BUDGET_MONTHS}},
        "periods": T,
        "instances": [{"module": i.module, **({"name": i.name} if i.name else {}), "settings": i.settings, "data": i.data} for i in model],
    }


if __name__ == "__main__":
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(recipe(), indent=1) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
