"""Write src/group-sample.js, the fictional group the probe's Group views show, from the consolidation proof.

    python tools/group-sample.py

Entities, ownership and groups come from prototypes/consolidation/group.py; each entity's own
surplus and net assets and each group's consolidated figures come from its reference, so the
pane shows the same numbers as the proof workbook. Fictional data only.
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(HERE.parent / "prototypes" / "consolidation"))
import group as G  # noqa: E402

b = G.book()
tb = G.trial_balances(b)
ref = G.reference(b)
Y = G.PERIODS
NA = [a for a, _, c in G.ACCOUNTS if c in ("asset", "liability")]


def own(e):
    return {"surplus": [round(-sum(tb[(e, a)][p] for a in G.PL), 3) for p in range(Y)],
            "na": [round(sum(tb[(e, a)][p] for a in NA), 3) for p in range(Y)]}


owns = {e: own(e) for e in G.CODES}
groups = []
for head, name in G.TIERS:
    r = ref[head]
    comb_s = [sum(owns[e]["surplus"][p] for e in r["members"]) for p in range(Y)]
    comb_n = [sum(owns[e]["na"][p] for e in r["members"]) for p in range(Y)]
    groups.append({"head": head, "name": name,
                   "surplus": [round(x, 3) for x in r["surplus"]], "na": [round(x, 3) for x in r["net_assets"]],
                   "elimSurplus": [round(r["surplus"][p] - comb_s[p], 3) for p in range(Y)],
                   "elimNa": [round(r["net_assets"][p] - comb_n[p], 3) for p in range(Y)],
                   "nciSurplus": [round(x, 3) for x in r["nci_pl"]], "nci": [round(x, 3) for x in r["nci"]]})
data = {
    "note": "Fictional group shaped like HFG's ($000), from prototypes/consolidation. Generated by tools/group-sample.py.",
    "years": G.YEAR_LABELS, "yearStart": G.YEAR_START,
    "entities": [{"code": c, "name": n, "parent": p, "held": h, "gst": g, "role": role, "status": G.STATUS[c],
                  "from": G.YEAR_START[G.START[c] - 1], "own": owns[c]} for c, n, p, h, g, role in G.ENTITIES],
    "groups": groups,
}
out = HERE / "src" / "group-sample.js"
out.write_text("/* Generated by tools/group-sample.py from prototypes/consolidation: do not edit by hand. */\n"
               "(function (root) { root.HfgGroupSample = " + json.dumps(data, indent=1, ensure_ascii=False) + "; })"
               "(typeof globalThis !== 'undefined' ? globalThis : this);\n")
print(out)
