// Bundle the add-in's features for the probe (New model, Insert module): the engine, the library (as
// JSON) and the entity logos in one browser script, written to addin-probe/src/addin.bundle.js
// (generated; do not edit).
//
//   node tools/build.ts [--out path] [--library path]

import { build, type Plugin } from 'esbuild';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { THEMES, type Brand } from '../../engine/src/index.ts';
import { ASSETS, pngSize } from '../../engine/src/node/assets.ts';
import { readLibraryBundle } from '../../engine/src/node/library.ts';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..', '..');
const args = process.argv.slice(2);
const opt = (name: string, fallback: string) => (args.includes(name) ? args[args.indexOf(name) + 1] : fallback);
const out = resolve(opt('--out', join(ROOT, 'addin-probe', 'src', 'addin.bundle.js')));
const demoPath = resolve(opt('--library', join(ROOT, 'prototypes', 'assembly', 'library')));
const hfgPath = join(ROOT, 'library', 'hfg');
// Whole models with their data, offered by New model.
const RECIPES = [
  { id: 'full_model', file: 'full_model.json', label: 'Full financial model (fictional data)',
    note: 'A property services company: revenue, cost and staff lines, working capital, assets, debt, equity, GST, income tax, scenarios, 18 months of history and the three statements.' },
  { id: 'budget_model', file: 'budget_model.json', label: 'Budget against actuals (fictional data)',
    note: 'A contractor with three business units: GL lines spread by seasonality profiles, the approved budget and monthly reforecasts saved, next year being built.' },
];
const recipes = RECIPES.filter(r => existsSync(join(hfgPath, 'recipes', r.file))).map(r => ({
  id: r.id, label: r.label, note: r.note, library: 'hfg', model: JSON.parse(readFileSync(join(hfgPath, 'recipes', r.file), 'utf8')),
}));

const logos: Record<string, { base64: string; width: number; height: number }> = {};
for (const brand of Object.keys(THEMES) as Brand[]) {
  const png = new Uint8Array(readFileSync(join(ASSETS, 'logos', THEMES[brand].logo.file)));
  logos[brand] = { base64: Buffer.from(png).toString('base64'), ...pngSize(png) };
}

const virtual: Plugin = {
  name: 'virtual',
  setup(b) {
    b.onResolve({ filter: /^virtual:/ }, a => ({ path: a.path, namespace: 'virtual' }));
    b.onLoad({ filter: /.*/, namespace: 'virtual' }, a => ({
      contents: JSON.stringify(a.path === 'virtual:library'
        ? { libraries: { demo: readLibraryBundle(demoPath), hfg: readLibraryBundle(hfgPath) }, recipes }
        : logos),
      loader: 'json',
    }));
  },
};

await build({
  entryPoints: [join(HERE, '..', 'src', 'probe-entry.ts')],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['es2020', 'safari15'],
  outfile: out,
  plugins: [virtual],
  legalComments: 'none',
  banner: { js: '/* Generated by addin/tools/build.ts: the add-in features for the probe. Do not edit. */' },
  logLevel: 'warning',
});
console.log(`wrote ${out}`);
