"""The full financial model demo: a fictional property services company, as a recipe the engine builds.

    python -m examples.full_model.recipe        # writes library/hfg/recipes/full_model.json

Everything here is fictional demo data. The business: property management fees, maintenance
services priced per job, and project management fees, with the staff, costs, assets, debt and
equity a company like that carries. Its history (April 2025 to September 2026) is generated by
running the model's own logic over the drivers that "happened", with noise, from the opening
balance sheet at 31 March 2025; the model then forecasts October 2026 to March 2028.
"""

from __future__ import annotations

import json
import random
from pathlib import Path

from .reference import Inst, run

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "library" / "hfg" / "recipes" / "full_model.json"

T = 36                 # April 2025 to March 2028
LAST_ACTUAL = 18       # September 2026
START = (2025, 4)
FY_END = 3
BUDGET_FIRST, BUDGET_MONTHS = 13, 12   # FY2027

SEED = 20261007
rng = random.Random(SEED)


def cal_month(t: int) -> int:
    return ((START[1] - 1 + t) % 12) + 1


def fy_index(t: int) -> int:
    """0 for FY2026, 1 for FY2027, 2 for FY2028."""
    return t // 12


def noisy(x: float, pct: float) -> float:
    return x * (1 + rng.uniform(-pct, pct))


def r2(x: float) -> float:
    return round(x, 2)


def stepped(base: float, rise: float) -> list[float]:
    """A value that rises by `rise` each April."""
    return [r2(base * (1 + rise) ** fy_index(t)) for t in range(T)]


def growing(base: float, monthly: float) -> list[float]:
    return [r2(base * (1 + monthly) ** t) for t in range(T)]


MAINT_SEASON = {1: 0.85, 2: 0.95, 3: 1.0, 4: 1.0, 5: 1.05, 6: 1.12, 7: 1.15, 8: 1.1, 9: 1.0, 10: 0.98, 11: 0.95, 12: 0.85}


def instances(model: bool) -> list[Inst]:
    """The recipe's instances. `model` False gives the history generator's version (amount drivers in
    place of growth-on-last-year, which needs a year of history the generator does not have)."""
    rng.seed(SEED)   # the same noise every call, so the model types the drivers the history came from
    n: dict[str, int] = {}

    def add(module: str, name: str | None = None, settings: dict | None = None, data: dict | None = None) -> Inst:
        n[module] = n.get(module, 0) + 1
        return Inst(module, n[module], settings or {}, name, data or {})

    actual = lambda t: t < LAST_ACTUAL
    pm_fees = [r2(noisy(240_000 * 1.006 ** t, 0.025) if actual(t) else 240_000 * 1.006 ** t) for t in range(T)]
    volume = [round(noisy(470 * MAINT_SEASON[cal_month(t)] * 1.004 ** t, 0.04) if actual(t) else 470 * MAINT_SEASON[cal_month(t)] * 1.004 ** t)
              for t in range(T)]
    price = stepped(720, 0.035)
    projects = [r2(noisy(110_000 * (0.9 if cal_month(t) in (12, 1) else 1.0) * 1.07 ** (t / 12), 0.08)) for t in range(T)]
    marketing = [r2(noisy(6_000 * (1.3 if cal_month(t) in (2, 3, 9) else 1.0) * 1.05 ** (t / 12), 0.05)) for t in range(T)]

    out = [
        add("fm.revenue", "Property management fees", {"method": 1, "gst": 1, "collect": 2}, {"series": {"amount": pm_fees},
            "scenarios": {"revenue": [0, 0.06, -0.10]}}),
        add("fm.revenue", "Maintenance services", {"method": 2, "gst": 1, "collect": 2}, {"series": {"price": price, "volume": volume},
            "scenarios": {"revenue": [0, 0.06, -0.10]}}),
        add("fm.revenue", "Project management fees", {"method": 3 if model else 1, "gst": 1, "collect": 3},
            {"series": {"growth": [0.07] * T} if model else {"amount": projects}, "scenarios": {"revenue": [0, 0.08, -0.15]}}),
        add("fm.cogs", "Maintenance materials", {"method": 1, "source": 2, "gst": 1, "stock": 2, "pay": 2},
            {"series": {"share": [0.30] * T}, "scenarios": {"cost": [0, 0, 0.03]}}),
        add("fm.cogs", "Subcontracted trades", {"method": 1, "source": 2, "gst": 1, "stock": 1, "pay": 2},
            {"series": {"share": [0.22] * T}, "scenarios": {"cost": [0, 0, 0.03]}}),
        add("fm.cogs", "Project consultants", {"method": 1, "source": 3, "gst": 1, "stock": 1, "pay": 2},
            {"series": {"share": [0.25] * T}, "scenarios": {"cost": [0, 0, 0.03]}}),
        add("fm.staff", "Property managers", {"kiwisaver": 0.03}, {"series": {"fte": [11] * 12 + [13] * 24, "salary": stepped(78_000, 0.035)},
            "scenarios": {"salaries": [0, 0.02, 0]}}),
        add("fm.staff", "Maintenance trades", {"kiwisaver": 0.03}, {"series": {"fte": [26] * 12 + [28] * 12 + [29] * 12, "salary": stepped(66_000, 0.035)},
            "scenarios": {"salaries": [0, 0.02, 0]}}),
        add("fm.staff", "Project managers", {"kiwisaver": 0.03}, {"series": {"fte": [5] * 15 + [6] * 21, "salary": stepped(112_000, 0.03)},
            "scenarios": {"salaries": [0, 0.02, 0]}}),
        add("fm.staff", "Support office", {"kiwisaver": 0.03}, {"series": {"fte": [8] * T, "salary": stepped(70_000, 0.03)},
            "scenarios": {"salaries": [0, 0.02, 0]}}),
        add("fm.opex", "Premises", {"method": 1, "gst": 1, "pay": 2}, {"series": {"amount": stepped(28_000, 0.03)}, "scenarios": {"cost": [0, 0, 0.05]}}),
        add("fm.opex", "Vehicles and fuel", {"method": 1, "gst": 1, "pay": 2},
            {"series": {"amount": [r2(noisy(36_000 * 1.003 ** t, 0.06) if actual(t) else 36_000 * 1.003 ** t) for t in range(T)]},
             "scenarios": {"cost": [0, 0, 0.05]}}),
        add("fm.opex", "IT and software", {"method": 3, "gst": 1, "pay": 2}, {"series": {"share": [0.02] * T}, "scenarios": {"cost": [0, 0, 0.05]}}),
        add("fm.opex", "Insurance", {"method": 1, "gst": 1, "pay": 1}, {"series": {"amount": stepped(7_500, 0.06)}, "scenarios": {"cost": [0, 0, 0.05]}}),
        add("fm.opex", "Marketing", {"method": 2 if model else 1, "gst": 1, "pay": 2},
            {"series": {"growth": [0.05] * T} if model else {"amount": marketing}, "scenarios": {"cost": [0, 0, 0.05]}}),
        add("fm.opex", "General and administration", {"method": 1, "gst": 1, "pay": 2},
            {"series": {"amount": [r2(noisy(14_000, 0.08) if actual(t) else 14_500) for t in range(T)]}, "scenarios": {"cost": [0, 0, 0.05]}}),
        add("fm.other_income", "Sundry income", {}, {"series": {"amount": [r2(noisy(1_800, 0.3) if actual(t) else 1_800) for t in range(T)]}}),
        add("fm.other_expense", "Donations", {}, {"series": {"amount": [2_500] * T}}),
        add("fm.collection", "Trade debtors", {"days": 20}, {"opening": {"closing": 443_000}}),
        add("fm.collection", "Council contracts", {"days": 45}, {"opening": {"closing": 190_000}}),
        add("fm.inventory", "Maintenance stock", {"days": 25, "gst": 1, "pay": 2}, {"opening": {"closing": 84_000}}),
        add("fm.payment", "Trade creditors", {"days": 30}, {"opening": {"closing": 343_000}}),
        add("fm.payroll", None, {"withheld": 0.22, "leave": 1.2}, {"opening": {"payable": 77_000, "leave": 370_000}}),
        add("fm.fixed_asset", "Motor vehicles", {"rate": 0.3}, {"opening": {"nbv": 640_000}}),
        add("fm.fixed_asset", "Plant and equipment", {"rate": 0.2}, {"opening": {"nbv": 280_000}}),
        add("fm.fixed_asset", "Office fit-out", {"rate": 0.1}, {"opening": {"nbv": 190_000}}),
        add("fm.intangible", "Software", {"rate": 0.4}, {"opening": {"nbv": 120_000}}),
        add("fm.capex", "Fleet replacement", {"class": 1, "gst": 1},
            {"series": {"amount": [110_000 if t == 3 else 45_000 if t == 10 else 60_000 if t == 19 else 120_000 if t == 28 else 0 for t in range(T)]}}),
        add("fm.capex", "Tools and plant", {"class": 2, "gst": 1}, {"series": {"amount": [r2(noisy(4_000, 0.4)) if actual(t) else 4_000 for t in range(T)]}}),
        add("fm.capex", "Office refurbishment", {"class": 3, "gst": 1}, {"series": {"amount": [85_000 if t == 6 else 0 for t in range(T)]}}),
        add("fm.capex", "Job management system", {"class": 4, "gst": 1}, {"series": {"amount": [40_000 if t == 5 else 60_000 if t == 23 else 0 for t in range(T)]}}),
        add("fm.debt", "Term loan", {"rate": 0.072}, {"series": {"draw": [0] * T, "repay": [15_000] * T},
            "opening": {"balance": 900_000}, "scenarios": {"rate_now": [0, -0.1, 0.2]}}),
        add("fm.debt", "Revolving credit facility", {"rate": 0.078},
            {"series": {"draw": [150_000 if t in (7, 20) else 0 for t in range(T)], "repay": [50_000 if t in (11, 12, 13, 23, 24, 25) else 0 for t in range(T)]},
             "opening": {"balance": 0}, "scenarios": {"rate_now": [0, -0.1, 0.2]}}),
        add("fm.equity", None, {"payout": 0.4, "delay": 3, "limit": True},
            {"series": {"issue": [0] * T}, "opening": {"capital": 600_000, "payable": 144_000}}),
        add("fm.gst", None, {"rate": 0.15, "cycle": 2}, {"opening": {"payable": 55_000}}),
        add("fm.income_tax", None, {"rate": 0.28, "uplift": 0.05}, {"opening": {"payable": 56_000}}),
        add("fm.interest_cash", None, {"rate": 0.025, "od_rate": 0.095}),
        add("fm.other_ca", "Prepayments", {}, {"series": {"change": [r2(rng.uniform(-3_000, 3_000)) for _ in range(T)]}, "opening": {"balance": 45_000}}),
        add("fm.other_nca", "Bonds held", {}, {"series": {"change": [0] * T}, "opening": {"balance": 60_000}}),
        add("fm.other_cl", "Accruals", {}, {"series": {"change": [r2(rng.uniform(-4_000, 4_000)) for _ in range(T)]}, "opening": {"balance": 38_000}}),
        add("fm.other_ncl", "Make-good provision", {}, {"series": {"change": [500] * T}, "opening": {"balance": 50_000}}),
        add("fm.other_equity", "Capital reserve", {}, {"series": {"change": [0] * T}, "opening": {"balance": 25_000}}),
        add("fm.statements", None, {}, {"opening": {"cash": 900_000}}),
        add("fm.checks"),
    ]
    return out


# The retained earnings that balance the opening balance sheet (31 March 2025).
OPENING_ASSETS = 900_000 + 443_000 + 190_000 + 84_000 + 45_000 + 60_000 + 640_000 + 280_000 + 190_000 + 120_000
OPENING_LIABILITIES = 343_000 + 77_000 + 55_000 + 56_000 + 144_000 + 38_000 + 370_000 + 900_000 + 0 + 50_000
OPENING_RETAINED = OPENING_ASSETS - OPENING_LIABILITIES - 600_000 - 25_000

# What a model cannot know but the generator needs: the GST for March 2025 accrued (its period ends
# in April), and the tax years before the model (FY2025 tax of 140,000 against FY2024's 120,000,
# two thirds of FY2025's provisional tax paid), and the FY2025 dividend declared in March 2025.
GEN_INIT = {
    "gst_period_end_prev": 0.0, "gst_accrued_prev": 55_000.0, "gst_due_prev": 0.0,
    "tax_ytd_prev": 140_000.0, "tax_last_year_prev": 120_000.0, "tax_two_years_prev": 100_000.0,
    "tax_paid_fy_prev": 2 * 120_000 * 1.05 / 3,
    "npat_ytd_prev": 0.0, "declared_before": [144_000.0, 0, 0, 0, 0, 0],
}

# Rows with a historical line: (module, row key, statement).
HISTORY_ROWS = {
    "fm.revenue": [("revenue", "is")], "fm.cogs": [("cost", "is")], "fm.staff": [("salaries", "is"), ("ks", "is")],
    "fm.opex": [("cost", "is")], "fm.other_income": [("income", "is")], "fm.other_expense": [("expense", "is")],
    "fm.collection": [("closing", "bs")], "fm.payment": [("closing", "bs")], "fm.inventory": [("closing", "bs")],
    "fm.payroll": [("payable", "bs"), ("leave", "bs"), ("movement", "is")],
    "fm.fixed_asset": [("dep", "is"), ("nbv", "bs")], "fm.intangible": [("amort", "is"), ("nbv", "bs")],
    "fm.debt": [("balance", "bs"), ("interest", "is")], "fm.equity": [("capital", "bs"), ("retained", "bs"), ("payable", "bs")],
    "fm.gst": [("payable", "bs")], "fm.income_tax": [("expense", "is"), ("payable", "bs")],
    "fm.interest_cash": [("interest", "is")],
    "fm.other_ca": [("balance", "bs")], "fm.other_nca": [("balance", "bs")], "fm.other_cl": [("balance", "bs")],
    "fm.other_ncl": [("balance", "bs")], "fm.other_equity": [("balance", "bs")], "fm.statements": [("cash", "bs")],
}


def generate() -> tuple[list[Inst], dict]:
    """The model's instances with their history, and the generator's full run (for reference)."""
    gen = instances(model=False)
    for i in gen:
        if i.module == "fm.equity":
            i.data.setdefault("opening", {})["retained"] = OPENING_RETAINED
    rows = run(gen, T, last_actual=0, fy_end=FY_END, start_month=START[1], start_year=START[0], init=GEN_INIT)
    model = instances(model=True)
    for g, m in zip(gen, model):
        m.data["opening"] = dict(g.data.get("opening", {}))
        keys = HISTORY_ROWS.get(m.module, [])
        if keys:
            src = "fs" if m.module == "fm.statements" else g.uid
            m.data["history"] = {k: [r2(v) for v in rows[f"{src}/{k}"][:LAST_ACTUAL]] for k, _ in keys}
    consistent(model, rows)
    return model, rows


def consistent(model: list[Inst], rows: dict) -> None:
    """Make the rounded history hold together to the cent, as a real ledger does: depreciation and the
    leave movement are what move their rounded balances, retained earnings move by the rounded
    profit less dividends, and cash is what balances the balance sheet."""
    L = LAST_ACTUAL
    H = lambda i, k: i.data["history"][k]
    op = lambda i, k: float(i.data.get("opening", {}).get(k, 0.0))
    by = lambda mod: [i for i in model if i.module == mod]
    classes = by("fm.fixed_asset") + by("fm.intangible")
    for k, c in enumerate(classes):
        flow = "dep" if c.module == "fm.fixed_asset" else "amort"
        adds = [sum(x.data["series"]["amount"][t] for x in by("fm.capex") if x.settings.get("class", 1) == k + 1) for t in range(L)]
        nbv = H(c, "nbv")
        H(c, flow)[:] = [r2((nbv[t - 1] if t else op(c, "nbv")) + adds[t] - nbv[t]) for t in range(L)]
    pay = by("fm.payroll")[0]
    leave = H(pay, "leave")
    H(pay, "movement")[:] = [r2(leave[t] - (leave[t - 1] if t else op(pay, "leave"))) for t in range(L)]
    # profit after tax from the rounded lines, as the statements add them
    def line(mod, key):
        return [sum(H(i, key)[t] for i in by(mod)) for t in range(L)]
    plus = [line("fm.revenue", "revenue"), line("fm.other_income", "income"), line("fm.interest_cash", "interest")]
    minus = [line("fm.cogs", "cost"), line("fm.staff", "salaries"), line("fm.staff", "ks"), [H(pay, "movement")[t] for t in range(L)],
             line("fm.opex", "cost"), line("fm.other_expense", "expense"), line("fm.fixed_asset", "dep"), line("fm.intangible", "amort"),
             line("fm.debt", "interest"), line("fm.income_tax", "expense")]
    npat = [sum(x[t] for x in plus) - sum(x[t] for x in minus) for t in range(L)]
    eq = by("fm.equity")[0]
    declared = [r2(v) for v in rows[f"{eq.uid.replace('#', '#')}/declared"][:L]]
    re = []
    for t in range(L):
        re.append(r2((re[t - 1] if t else op(eq, "retained")) + npat[t] - declared[t]))
    H(eq, "retained")[:] = re
    # cash balances the balance sheet
    bal = lambda mod, key: [sum(H(i, key)[t] for i in by(mod)) for t in range(L)]
    other_assets = [sum(x[t] for x in (bal("fm.collection", "closing"), bal("fm.inventory", "closing"), bal("fm.other_ca", "balance"),
                                       bal("fm.fixed_asset", "nbv"), bal("fm.intangible", "nbv"), bal("fm.other_nca", "balance"))) for t in range(L)]
    liabilities = [sum(x[t] for x in (bal("fm.payment", "closing"), [H(pay, "payable")[t] for t in range(L)], bal("fm.gst", "payable"),
                                      bal("fm.income_tax", "payable"), [H(eq, "payable")[t] for t in range(L)], bal("fm.other_cl", "balance"),
                                      [H(pay, "leave")[t] for t in range(L)], bal("fm.debt", "balance"), bal("fm.other_ncl", "balance"))) for t in range(L)]
    equity = [H(eq, "capital")[t] + re[t] + bal("fm.other_equity", "balance")[t] for t in range(L)]
    fs = by("fm.statements")[0]
    H(fs, "cash")[:] = [r2(liabilities[t] + equity[t] - other_assets[t]) for t in range(L)]


def recipe() -> dict:
    model, _ = generate()
    return {
        "title": "Property services operating model",
        "entity": {"name": "Home Foundation Services", "brand": "HF"},
        "preparedBy": "Prepared by Group Finance",
        "notes": [
            "Fictional demo data: a property services company with three revenue lines, built by the HFG model engine.",
            "Actual months (April 2025 to September 2026) read the historical income statement and balance sheet; later months are forecast.",
            "Inputs are the shaded cells; drop-downs choose drivers, profiles and classes from the lists on the Lookups sheet.",
        ],
        "timeline": {"start": f"{START[0]}-{START[1]:02d}", "fyEndMonth": FY_END, "lastActual": LAST_ACTUAL, "denomination": "$000",
                     "budget": {"first": BUDGET_FIRST, "months": BUDGET_MONTHS}},
        "periods": T,
        "instances": [{"module": i.module, **({"name": i.name} if i.name else {}), "settings": i.settings, "data": i.data} for i in model],
    }


if __name__ == "__main__":
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(recipe(), indent=1) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
